### ISSUE TITLE
Error with installing package

### ISSUE THREAD

**Issue by mountaindboz** [ODWG/ODWGtools#2]
Thanks for working on #1
I tried to re-install the package using 

```remotes::install_github("ODWG/ODWGtools")```

and I got the following error message in the R console. I got the same error after un-installing the ODWGtools package and restarting my R session.

Downloading GitHub repo ODWG/ODWGtools@master
√  checking for file 'C:\Users\dboswort\AppData\Local\Temp\Rtmpig8TIP\remotes50444398333d\ODWG-ODWGtools-57a4599/DESCRIPTION' (593ms)
-  preparing 'ODWGtools': (909ms)
√  checking DESCRIPTION meta-information ... 
-  checking for LF line-endings in source and make files and shell scripts (482ms)
-  checking for empty or unneeded directories
-  looking to see if a 'data/datalist' file should be added
-  building 'ODWGtools_0.5.0.9000.tar.gz'
   
Installing package into ‘C:/Users/dboswort/Documents/R/win-library/3.6’
(as ‘lib’ is unspecified)
* installing *source* package 'ODWGtools' ...
** using staged installation
** R
Error in .install_package_code_files(".", instdir) : 
files in 'Collate' field missing from 'C:/Users/dboswort/AppData/Local/Temp/Rtmpk51bEF/R.INSTALL47a4760c78b4/ODWGtools/R':
  anomaly.r
ERROR: unable to collate and parse R files for package 'ODWGtools'
* removing 'C:/Users/dboswort/Documents/R/win-library/3.6/ODWGtools'
Error: Failed to install 'ODWGtools' from GitHub:
  (converted from warning) installation of package ‘C:/Users/dboswort/AppData/Local/Temp/Rtmpig8TIP/file50444eb23a93/ODWGtools_0.5.0.9000.tar.gz’ had non-zero exit status

**Comment by mkoohafkan** [comment]
try the latest commit, should work now. This package is under active development and I can't guarantee that every commit will result in a package that passes all tests in `install.packages()`/`remotes::install_github()`, so you will probably be better off cloning the repository and using `devtools::load_all()`.
